apiVersion: v1
kind: ServiceAccount
metadata:
  name: jinja-template-operator-controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: jinja-template-operator
    app.kubernetes.io/managed-by: kustomize
